"""widen_balance_sheet_ratios_and_note_title

Revision ID: 4c1295970e3a
Revises: a76b79640393
Create Date: 2026-03-10 02:38:42.526788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1295970e3a'
down_revision: Union[str, None] = 'a76b79640393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_analyst_notes', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('stock_balance_sheets', 'current_ratio',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_balance_sheets', 'ltd_to_cap_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_balance_sheets', 'net_income_to_revenue_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_balance_sheets', 'return_on_assets_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_balance_sheets', 'return_on_equity_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_balance_sheets', 'return_on_equity_pct',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('stock_balance_sheets', 'return_on_assets_pct',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('stock_balance_sheets', 'net_income_to_revenue_pct',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('stock_balance_sheets', 'ltd_to_cap_pct',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('stock_balance_sheets', 'current_ratio',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('stock_analyst_notes', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
