"""add missing parser fields

Revision ID: 75ef54aaed55
Revises: b7c84913beb1
Create Date: 2026-03-02 07:25:20.617412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ef54aaed55'
down_revision: Union[str, None] = 'b7c84913beb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_key_stats', sa.Column('quality_ranking', sa.String(length=20), nullable=True))
    op.add_column('stock_key_stats', sa.Column('oper_eps_current_e', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('stock_key_stats', sa.Column('oper_eps_next_e', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('stock_key_stats', sa.Column('pe_on_oper_eps_current', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_reports', sa.Column('zacks_rank_label', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_reports', 'zacks_rank_label')
    op.drop_column('stock_key_stats', 'pe_on_oper_eps_current')
    op.drop_column('stock_key_stats', 'oper_eps_next_e')
    op.drop_column('stock_key_stats', 'oper_eps_current_e')
    op.drop_column('stock_key_stats', 'quality_ranking')
    # ### end Alembic commands ###
