"""create_v2_schema_13_tables

Revision ID: a76b79640393
Revises: 27d9d97ac1c0
Create Date: 2026-03-05 21:28:07.221624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a76b79640393'
down_revision: Union[str, None] = '27d9d97ac1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('gics_sector', sa.String(length=100), nullable=True),
    sa.Column('gics_sub_industry', sa.String(length=100), nullable=True),
    sa.Column('zacks_industry', sa.String(length=100), nullable=True),
    sa.Column('zacks_industry_rank', sa.String(length=100), nullable=True),
    sa.Column('investment_style', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domicile', sa.String(length=50), nullable=True),
    sa.Column('founded_year', sa.SmallInteger(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('officers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('board_members', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('index_memberships', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('analyst_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyst_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('stock_price_at_note', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_sheets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('long_term_debt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_capital', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('capital_expenditures', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_from_operations', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('ltd_to_cap_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('net_income_to_revenue_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('return_on_assets_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('return_on_equity_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('CFRA', 'Zacks')", name='chk_balance_sheets_source'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source', 'fiscal_year', name='uq_balance_sheets_company_source_year')
    )
    op.create_table('company_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source', 'event_date', 'headline', name='uq_company_events_company_source_date_headline')
    )
    op.create_table('financials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('fiscal_quarter', sa.SmallInteger(), nullable=True),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pretax_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('depreciation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_expense', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('effective_tax_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_normalized', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gross_margin_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('operating_margin_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('segment_revenues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eps_surprise_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sales_surprise_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period_type IN ('annual', 'quarterly')", name='chk_financials_period_type'),
    sa.CheckConstraint("source IN ('CFRA', 'Zacks')", name='chk_financials_source'),
    sa.CheckConstraint('fiscal_quarter BETWEEN 1 AND 4', name='chk_financials_quarter'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source', 'fiscal_year', 'fiscal_quarter', 'is_estimate', name='uq_financials_company_source_year_quarter_estimate')
    )
    op.create_table('income_statements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('depreciation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_expense', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pretax_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('effective_tax_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sp_core_eps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('CFRA', 'Zacks')", name='chk_income_statements_source'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source', 'fiscal_year', name='uq_income_statements_company_source_year')
    )
    op.create_table('per_share_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('tangible_book_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('earnings', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('earnings_normalized', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dividends', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('payout_ratio_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('price_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pe_high', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pe_low', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('CFRA', 'Zacks')", name='chk_per_share_data_source'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source', 'fiscal_year', name='uq_per_share_data_company_source_year')
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('analyst_name', sa.String(length=100), nullable=True),
    sa.Column('raw_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('CFRA', 'Zacks')", name='chk_reports_source'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source', 'report_date', name='uq_reports_company_source_date')
    )
    op.create_table('consensus_estimates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('buy_count', sa.SmallInteger(), nullable=True),
    sa.Column('buy_hold_count', sa.SmallInteger(), nullable=True),
    sa.Column('hold_count', sa.SmallInteger(), nullable=True),
    sa.Column('weak_hold_count', sa.SmallInteger(), nullable=True),
    sa.Column('sell_count', sa.SmallInteger(), nullable=True),
    sa.Column('no_opinion_count', sa.SmallInteger(), nullable=True),
    sa.Column('total_analysts', sa.SmallInteger(), nullable=True),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('eps_avg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_high', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_low', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_est_count', sa.SmallInteger(), nullable=True),
    sa.Column('estimated_pe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'snapshot_date', 'fiscal_year', name='uq_consensus_estimates_company_date_year')
    )
    op.create_table('peer_comparisons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('peer_ticker', sa.String(length=10), nullable=False),
    sa.Column('peer_name', sa.String(length=200), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('rank', sa.SmallInteger(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'peer_ticker', name='uq_peer_comparisons_report_ticker')
    )
    op.create_table('report_key_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('week_52_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('week_52_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('beta', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_volume_20d', sa.BigInteger(), nullable=True),
    sa.Column('ytd_price_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trailing_12m_eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('trailing_12m_pe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('oper_eps_current_e', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('oper_eps_next_e', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pe_on_oper_eps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pe_forward_12m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_cap_b', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('shares_outstanding_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('institutional_ownership_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dividend_yield_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('dividend_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eps_cagr_3yr_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_to_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_to_ebitda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_to_pretax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_to_book', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_to_cashflow', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('peg_ratio', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('debt_equity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cash_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('earnings_yield_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_margin_1yr_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('net_margin_3yr_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sales_growth_1yr_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sales_growth_3yr_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('earnings_esp_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('last_eps_surprise_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('last_sales_surprise_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('expected_report_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('report_ratings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('stars_rating', sa.SmallInteger(), nullable=True),
    sa.Column('risk_assessment', sa.String(length=10), nullable=True),
    sa.Column('fair_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fair_value_rank', sa.SmallInteger(), nullable=True),
    sa.Column('volatility', sa.String(length=10), nullable=True),
    sa.Column('technical_eval', sa.String(length=10), nullable=True),
    sa.Column('insider_activity', sa.String(length=15), nullable=True),
    sa.Column('investment_style', sa.String(length=30), nullable=True),
    sa.Column('quality_ranking', sa.String(length=5), nullable=True),
    sa.Column('zacks_rank', sa.SmallInteger(), nullable=True),
    sa.Column('zacks_rank_label', sa.String(length=20), nullable=True),
    sa.Column('prior_recommendation', sa.String(length=20), nullable=True),
    sa.Column('style_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fair_value_rank BETWEEN 1 AND 5', name='chk_report_ratings_fv_rank'),
    sa.CheckConstraint('stars_rating BETWEEN 1 AND 5', name='chk_report_ratings_stars'),
    sa.CheckConstraint('zacks_rank BETWEEN 1 AND 5', name='chk_report_ratings_zacks_rank'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('report_text_sections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('section_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'section_type', name='uq_report_text_sections_report_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_text_sections')
    op.drop_table('report_ratings')
    op.drop_table('report_key_stats')
    op.drop_table('peer_comparisons')
    op.drop_table('consensus_estimates')
    op.drop_table('reports')
    op.drop_table('per_share_data')
    op.drop_table('income_statements')
    op.drop_table('financials')
    op.drop_table('company_events')
    op.drop_table('balance_sheets')
    op.drop_table('analyst_notes')
    op.drop_table('companies')
    # ### end Alembic commands ###
