"""initial 7 tables

Revision ID: b7c84913beb1
Revises: 
Create Date: 2026-03-02 06:25:52.971894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7c84913beb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('gics_sector', sa.String(length=100), nullable=True),
    sa.Column('gics_sub_industry', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('domicile', sa.String(length=100), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geo_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('officers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('board_members', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('index_memberships', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange', name='uq_profile_ticker_exchange')
    )
    op.create_index(op.f('ix_stock_profiles_ticker'), 'stock_profiles', ['ticker'], unique=False)
    op.create_table('stock_analyst_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('analyst_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('stock_price_at_note', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_profile_id'], ['stock_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_balance_sheets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('long_term_debt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_capital', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('capital_expenditures', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_from_operations', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ltd_to_cap_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('net_income_to_revenue_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('return_on_assets_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('return_on_equity_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_profile_id'], ['stock_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_profile_id', 'fiscal_year', name='uq_balance_sheet_profile_year')
    )
    op.create_table('stock_financials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pretax_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eps_normalized', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('free_cash_flow_ps', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('tangible_book_value_ps', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('depreciation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_tax_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('gross_margin_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('operating_margin_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('segment_revenues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eps_surprise_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sales_surprise_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_profile_id'], ['stock_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_profile_id', 'fiscal_year', 'fiscal_quarter', 'is_estimate', name='uq_financial_profile_year_quarter_estimate')
    )
    op.create_table('stock_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('analyst_name', sa.String(length=100), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('prior_recommendation', sa.String(length=20), nullable=True),
    sa.Column('stars_rating', sa.Integer(), nullable=True),
    sa.Column('zacks_rank', sa.Integer(), nullable=True),
    sa.Column('style_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=True),
    sa.Column('risk_assessment', sa.String(length=20), nullable=True),
    sa.Column('fair_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fair_value_rank', sa.Integer(), nullable=True),
    sa.Column('volatility', sa.String(length=20), nullable=True),
    sa.Column('technical_eval', sa.String(length=20), nullable=True),
    sa.Column('insider_activity', sa.String(length=20), nullable=True),
    sa.Column('investment_style', sa.String(length=50), nullable=True),
    sa.Column('industry_rank', sa.String(length=100), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('reasons_to_buy', sa.Text(), nullable=True),
    sa.Column('reasons_to_sell', sa.Text(), nullable=True),
    sa.Column('investment_rationale', sa.Text(), nullable=True),
    sa.Column('business_summary', sa.Text(), nullable=True),
    sa.Column('sub_industry_outlook', sa.Text(), nullable=True),
    sa.Column('last_earnings_summary', sa.Text(), nullable=True),
    sa.Column('outlook', sa.Text(), nullable=True),
    sa.Column('recent_news', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_profile_id'], ['stock_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_profile_id', 'source', 'report_date', name='uq_report_profile_source_date')
    )
    op.create_table('stock_key_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_report_id', sa.BigInteger(), nullable=False),
    sa.Column('week_52_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('week_52_low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('trailing_12m_eps', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trailing_12m_pe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_cap_b', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shares_outstanding_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('beta', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('eps_cagr_3yr_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('institutional_ownership_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dividend_yield_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dividend_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_to_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_to_ebitda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_to_pretax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_margin_1yr_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('net_margin_3yr_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sales_growth_1yr_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sales_growth_3yr_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pe_forward_12m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ps_forward_12m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('peg_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_to_book', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_to_cashflow', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('debt_equity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_per_share', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('earnings_yield_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('valuation_multiples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_report_id'], ['stock_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_report_id')
    )
    op.create_table('stock_peers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_report_id', sa.BigInteger(), nullable=False),
    sa.Column('peer_ticker', sa.String(length=10), nullable=True),
    sa.Column('peer_name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('recent_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('market_cap_m', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('price_chg_30d_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('price_chg_1yr_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fair_value_calc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('yield_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('roe_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ltd_to_cap_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('detailed_comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_report_id'], ['stock_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_peers')
    op.drop_table('stock_key_stats')
    op.drop_table('stock_reports')
    op.drop_table('stock_financials')
    op.drop_table('stock_balance_sheets')
    op.drop_table('stock_analyst_notes')
    op.drop_index(op.f('ix_stock_profiles_ticker'), table_name='stock_profiles')
    op.drop_table('stock_profiles')
    # ### end Alembic commands ###
